### ISSUE TITLE
Add smooch io

### ISSUE THREAD

**Issue by jundl77** [hackundsoehne/och-website#10]

**Comment by CyrilPepito** [comment]
Hello @jundl77 
I stumbled upon your issue while browsing Github, have you heard of [Broid](www.broid.ai)?
We offer a web messenger for websites that you can plug with any other messaging apps like Slack with our API.
Basically you can use Broid's API to converse on 20+ messaging channels (including that web messenger) using your favorite app to manager those conversations.
And it's free during our beta!

Also open source -> [Github repo](https://github.com/broidHQ/integrations)

**Comment by jundl77** [comment]
But the same goes for smooch io, and it's free all the way

but thanks for the offer

**Comment by adrianleh** [comment]
Implemented in 45e31dceecde31c620650c6c31be95ee8bcdeafd
