### ISSUE TITLE
Add KIT Logo, Fix other Logos

### ISSUE THREAD

**Issue by reiner-dolp** [hackundsoehne/och-website#5]
- [x] add KIT Logo
- [x] all logos are currently embeded in color and converted to grayscale using a CSS filter. As a result, each logo is displayed in a different shade of gray. ~All Logos should be converted to the same gray color in an image editing software.~ All logos should be displayed in black
- [x] the css filter "desaturate" should be removed.
- [x] H&S Logo should come first

**Comment by LeanderK** [comment]
I don't think we are allowed to alter the logos of the KIT or the ZKM in any way. A black version of the KIT logo exists.

**Comment by reiner-dolp** [comment]
All Logos are already displayed in grayscale, which might be against the style guide of some institutions. You can however tell that for each institution, the shade of gray is different:

![image](https://user-images.githubusercontent.com/770508/30520868-59142f46-9bb6-11e7-8dff-a6684e84584c.png)

**Comment by LeanderK** [comment]
waiting for approval from the KIT-brandmanagement

**Comment by reiner-dolp** [comment]
@LeanderK the patch should also delete the "desaturate" CSS class.

**Comment by LeanderK** [comment]
done

**Comment by jundl77** [comment]
Did we get the approval?

**Comment by LeanderK** [comment]
not yet, I will create a pull-request when I get the approval.
